### ISSUE TITLE
cannot compile, code page issue

### ISSUE THREAD

**Issue by pdinc-oss** [dehasi/groovy-dc#1]
$ /gradle-3.5/bin/gradle jar
The executable property on ForkOptions has been deprecated and is scheduled to be removed in Gradle 5.0. Please use javaHome instead.
        at build_3yi5hn3nz2v7to7f5m9lukd5d$_run_closure1.doCall(C:\Users\Public\Desktop\projects\groovy-dc\build.gradle:8)
:compileJava
Download https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/2.3.11/groovy-all-2.3.11.pom
Download https://repo1.maven.org/maven2/com/intellij/openapi/7.0.3/openapi-7.0.3.pom
Download https://repo1.maven.org/maven2/com/intellij/annotations/9.0.4/annotations-9.0.4.pom
Download https://repo1.maven.org/maven2/com/intellij/extensions/7.0.3/extensions-7.0.3.pom
Download https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/2.3.11/groovy-all-2.3.11.jar
Download https://repo1.maven.org/maven2/com/intellij/openapi/7.0.3/openapi-7.0.3.jar
Download https://repo1.maven.org/maven2/com/intellij/annotations/9.0.4/annotations-9.0.4.jar
Download https://repo1.maven.org/maven2/com/intellij/extensions/7.0.3/extensions-7.0.3.jar
C:\Users\Public\Desktop\projects\groovy-dc\src\main\java\decompiler\visitors\SVisitor.java:24: error: unmappable character for encoding Cp1252
    public static final String classType = "Ñ?lassType";
                                             ^
1 error
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed with exit code 1; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 53.47 secs

**Comment by dehasi** [comment]
It was mistyping in the string variable. 
I've just fixed it.
